### ISSUE TITLE
Part location

### ISSUE THREAD

**Issue by lookme2** [inventree/inventree-python#45]
I am  using `Part.list(api, search=<search string>)`  to retrieve a part number from invenTree.  What I can't seem to get back in the location of that part which is human readable.  Is there some other way of doing this?

**Comment by SchrodingersGat** [comment]
The `Part` API does not return any location information, because the **Part** objects are not the same as **Stock** objects.

Stock items are concrete instances of Parts, and these have associated locations.

You will need to use the `Stock` API to get this data.

For example, if the Part ID is 100:

GET `/api/stock/?part=100`

will return all stock items for part 100

You can also include verbose location information for each stock item:

GET `/api/stock/?part=100&location_detail=1`

**Comment by SchrodingersGat** [comment]
In terms of the Python API, if you already have a Part object, you could call:

`Part.getStockItems()`

https://github.com/inventree/inventree-python/blob/53a101fbd4853c6a06b53fa13e5f134c1c126f63/inventree/part.py#L74

**Comment by lookme2** [comment]
Using `Part.getStockItems()` returns a list of stock locations as in an integer.  I was looking for the human readable version of it.  So I can get 'location=484' but I would like that to say 'location=D9 04'.  Or what ever I have my location labeled.

**Comment by SchrodingersGat** [comment]
Ok I see what you mean.

One way to get around this is to take the integer key for the stock location (let's say the location ID is `123`) and do the following:

```python
location = inventree.stock.StockLocation(api, pk=123)
```

Also refer to https://github.com/inventree/inventree-python/pull/46 which adds the function `getStockLocation()` to the StockItem class so you can directly access the location object if you already have the stock item.

**Comment by SchrodingersGat** [comment]
Please let me know if this has adequately addressed your issue :)

**Comment by lookme2** [comment]
This worked.  Thanks!
